//PROJECT
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";
export const GET_ALL_PROJECT_CATEGORY = " GET_ALL_PROJECT_CATEGORY";
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA';
export const GET_LIST_PROJECT = "GET_LIST_PROJECT";
//USERS
export const USER_SIGNIN_API = "USER_SIGNIN_API";
export const USLOGIN = "USLOGIN";

//DRAWER : FORM + SUBMIT BUTON
export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";
